presubmits:
  ibm/deploy:
    - agent: kubernetes
      always_run: true
      branches:
        - master
      context: ci/prow/build
      decorate: true
      decoration_config:
        skip_cloning: true
      labels:
        ci-operator.openshift.io/prowgen-controlled: "true"
        pj-rehearse.openshift.io/can-be-rehearsed: "true"
      name: deploy-ibm-cloud-cluster
      spec:
        imagePullSecrets:
        - name: registry-default-secret
        containers:
          - args:
            command:
              - ./deploy_travis.sh
            env:
              - name: artifactDir
                value: /var/logs/e2e/
              - name: BX_API_KEY
                valueFrom:
                  secretKeyRef:
                    key: bx_api_key
                    name: ibm-gate-test-secrets
              - name: BX_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    key: bx_endpoint
                    name: ibm-gate-test-secrets
              - name: tugboat_id
                valueFrom:
                  secretKeyRef:
                    key: tugboat_id
                    name: ibm-gate-test-secrets
              - name: SL_USE
                valueFrom:
                  secretKeyRef:
                    key: sl_use
                    name: ibm-gate-test-secrets
              - name: SL_PASS
                valueFrom:
                  secretKeyRef:
                    key: sl_pass
                    name: ibm-gate-test-secrets
              - name: cos_backup_bucket
                valueFrom:
                  secretKeyRef:
                    key: cos_backup_bucket
                    name: ibm-gate-test-secrets
              - name: cos_backups_endpoint
                valueFrom:
                  secretKeyRef:
                    key: cos_backups_endpoint
                    name: ibm-gate-test-secrets
              - name: cos_access_key
                valueFrom:
                  secretKeyRef:
                    key: cos_access_key
                    name: ibm-gate-test-secrets
              - name: cos_secret_access_key
                valueFrom:
                  secretKeyRef:
                    key: cos_secret_access_key
                    name: ibm-gate-test-secrets
              - name: MY_POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            image: registry.ng.bluemix.net/armada/openshift4-gate:master
            imagePullPolicy: Always
            name: ""
            resources:
              requests:
                cpu: 10m
            volumeMounts:
              - mountPath: /etc/ibm-gate-test-secrets
                name: ibm-gate-test-secrets
                readOnly: true
        serviceAccountName: ci-operator
        volumes:
          - name: ibm-gate-test-secrets
            secret:
              secretName: ibm-gate-test-secrets
      trigger: (?m)^/test( | .* )build,?($|\s.*)
