build_root:
  image_stream_tag:
    name: "iks"
    namespace: ibm-gate-secrets
    tag: "4.3"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: create-cluster
  commands: chmod 600 /root/.ssh/id_rsa && export inject=false &&  ./deploy_travis.sh
  container:
    from: root
  secret:
    name: 'ibm-gate-test-secrets'
    mount_path: '/usr/ibm-gate-test-secrets/'

